apply plugin: "com.android.library"
apply plugin: "kotlin-android"
apply plugin: 'dagger.hilt.android.plugin'
apply from: '../versions.gradle'

android {
  kotlinOptions { jvmTarget = "21" }
  compileOptions {
    coreLibraryDesugaringEnabled true
    sourceCompatibility JavaVersion.VERSION_21
    targetCompatibility JavaVersion.VERSION_21
  }

  compileSdkVersion versions.compileSdk

  defaultConfig {
    minSdkVersion versions.minSdk
    targetSdkVersion versions.targetSdk
    compileSdkVersion versions.compileSdk

    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }

  buildTypes {
    release {
      minifyEnabled false
    }
  }

  namespace 'xyz.stignarnia.data_webdav'
}

dependencies {
  implementation project(':common')

  api libs.okhttp

  implementation libs.coroutines
  implementation libs.timber

  implementation libs.hilt.android
  ksp libs.hilt.compiler

  testImplementation libs.junit
  testImplementation libs.truth
  testImplementation libs.mockwebserver
  testImplementation libs.coroutinesTest

  coreLibraryDesugaring libs.android.desugar
}
