apply plugin: "com.android.library"
apply plugin: 'dagger.hilt.android.plugin'
apply from: '../versions.gradle'

android {
  compileOptions {
    coreLibraryDesugaringEnabled = true
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
  }

  defaultConfig {
    minSdk = versions.minSdk
    targetSdk = versions.targetSdk
    testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
  }

  buildTypes {
    release {
      minifyEnabled = false
    }
  }

  namespace = 'xyz.stignarnia.data_webdav'
}

dependencies {
  implementation project(':common')

  api libs.okhttp

  implementation libs.coroutines
  implementation libs.timber

  implementation libs.hilt.android
  ksp libs.hilt.compiler

  testImplementation libs.junit
  testImplementation libs.truth
  testImplementation libs.mockwebserver
  testImplementation libs.coroutinesTest

  coreLibraryDesugaring libs.android.desugar
}
