apply plugin: 'com.android.library'
apply plugin: 'dagger.hilt.android.plugin'
apply from: '../versions.gradle'

android {
  compileOptions {
    coreLibraryDesugaringEnabled = true
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
  }

  defaultConfig {
    minSdk = versions.minSdk
    targetSdk = versions.targetSdk
    testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
  }

  buildFeatures {
    viewBinding = true
  }

  buildTypes {
    release {
      minifyEnabled = false
    }
  }

  namespace = 'xyz.stignarnia.ui_movie'
}

dependencies {
  implementation project(':common')
  implementation project(':data-local')
  implementation project(':data-remote')
  implementation project(':repository')
  implementation project(':ui-base')
  implementation project(':ui-model')
  implementation project(':ui-people')
  implementation project(':ui-navigation')
  implementation project(':ui-streamings')

  implementation libs.hilt.android
  ksp libs.hilt.compiler

  implementation libs.circleIndicator

  coreLibraryDesugaring libs.android.desugar
}
